### ISSUE TITLE
FOR HELP!

### ISSUE THREAD

**Issue by SJiPeng** [cMadan/openMorph#13]
Please help me get rfMRI date for twins of DZ and MZ.

**Comment by cMadan** [comment]
Hi @SJiPeng, this repo is for listing existing datasets for brain morphology data. Your question would be better suited to a larger community such as the SPM mailing list or NITRC discussion forum. That said, I believe the HCP data includes twins, but I think the twin dyad information requires a more detailed data use application. (I haven't done this myself.)
