### ISSUE TITLE
Convert DOIs to links in README

### ISSUE THREAD

**Issue by KirstieJane** [cMadan/openMorph#9]
This list is fantastic @cmadan!! I’m making this issue so I can tweet it to see if anyone wants to help you out :smile:. Please don’t think I’m asking you for more work!

The README file currently contains references with DOIs but these DOIs could also be links to the resource.

And example would be converting:

```
Di Martino et al. (2014) Mol Psychiatry [10.1038/mp.2013.78]
```

to

```
Di Martino et al. (2014) Mol Psychiatry [10.1038/mp.2013.78](https://dx.doi.org/10.1038/mp.2013.78)
```

which would then look like:

Di Martino et al. (2014) Mol Psychiatry [10.1038/mp.2013.78](https://dx.doi.org/10.1038/mp.2013.78)

**Comment by KirstieJane** [comment]
These look great to me! Thank you @composition4!

I don't have write access, and I'm sure @cMadan is super busy, but I'm also confident he'll take a look as soon as he's able to  😄

**Comment by composition4** [comment]
* both v welcome 💜 !
* keep thit sed command handy
* never know when u need again!

**Comment by cMadan** [comment]
This was a great fix, thank you both!

**Comment by composition4** [comment]
commit 39580c0b breaks formatting though

**Comment by composition4** [comment]
oh nm u got it 😸
